### PR TITLE
Change Singaporeans to Singapore Population

### PR DESCRIPTION
**Pull request by VincentNgVS**
More accurately reflecting the calculation with reference Singapore population census.

Pull request to dev branch.

### CODE REVIEW

**Comment by njyjn** [comment]
I'm not 100% convinced this change should be made in the main header, which should be kept as concise as possible. Would it make more sense to explain what the definition of `Singaporeans` is in the footer instead?

If we do decide to go with this change, my suggestion is to phrase it  like `X% of the Singapore population is` as the quantifier would agree with the singular noun 'population'.

**Comment by VincentNgVS** [comment]
OK. You decide. I just want to test the CI/CD process.

My Docker is ready. Please advise how to proceed to set up the unit testing
environment
.

**Comment by njyjn** [comment]
The terminology has been updated accordingly per your suggestion. If you agree, we can merge and close this.

Screen Shot 2021-06-13 at 11 58 25 AM

**Comment by VincentNgVS** [comment]
Yes, I agree. Merge & deploy it to main.

**Pull request merged**
